name: Run Komodo Action
description: Run a Komodo action
inputs:
  komodo-url:
    description: URL of the Komodo instance to connect to
    required: true
  komodo-api-key:
    description: API key for authenticating with the Komodo instance
    required: true
  komodo-api-secret:
    description: API secret for authenticating with the Komodo instance
    required: true
  action:
    description: Name or ID of Komodo action to run
    required: true
  args:
    description: Arguments to pass into the Komodo action, in JSON format
    required: false
    default: '{}'
runs:
  using: composite
  steps:
    - name: Invoke action
      shell: bash
      run: |
        curl --header "X-Api-Key: ${{ inputs.komodo-api-key }}" \
          --header "X-Api-Secret: ${{ inputs.komodo-api-secret }}" \
          --json '{"type": "RunAction", "params": {"action": "${{ inputs.action }}", "args": ${{ inputs.args }}}}' \
          ${{ inputs.komodo-url }}/execute
